### ISSUE TITLE
Easier rule parsing

### ISSUE THREAD

**Issue by cfbevan** [cfbevan/murdle-solver#2]
Using TOML for rules is difficult. Add a custom parser so that writing rules is easier. Preferably in a lisp style syntax.

Ex: 

```toml
[[rules]]
op = "not"

[rules.right]
op = "fact"
right = ["a", "*"]
```

can be written as

```
rules = [
    '(not ("a" "*"))'
]
```

Ex:

```toml
[[rules]]
op = "fact"
right = ["*", "d"]
```

can be written as

```
rules = [
    '("*" "d")'
]
```

With this the rules become like the groups and can be a simple list of strings. For the `test.toml` file we get:

```
rules = [
    '(not ("a" "*"))',
    '("*" "d")'
]
```

This is much easier to read and understand.
